language: objective-c
script:
- xctool -workspace VenmoColorsSample.xcworkspace-scheme VenmoColorsSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_install:
- brew uninstall xctool; brew install xctool --HEAD;
