language: objective-c
script:
- xctool -project VenmoColors.xcodeproj -scheme VenmoColors -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_install:
- brew uninstall xctool; brew install xctool --HEAD;
